export function generateClinicianSummary(profile, intervention, record) {
  const baseline = record.baseline.length
    ? record.baseline.map((signal) => `- ${signal.label}: ${signal.value} ${signal.unit} (${signal.dataQuality}; ${signal.note})`).join('\n')
    : '- No targeted baseline signals were available.';

  const exposure = record.exposure.length
    ? record.exposure.map((obs) => `- ${obs.label}: ${obs.value} ${obs.unit} on ${obs.date}. ${obs.note}`).join('\n')
    : '- No exposure/adherence observations recorded.';

  const outcomes = record.outcomes.length
    ? record.outcomes.map((obs) => `- ${obs.label}: ${obs.value} ${obs.unit} on ${obs.date}. ${obs.note}`).join('\n')
    : '- No outcome observations recorded.';

  const safety = record.safety.length
    ? record.safety.map((flag) => `- ${flag.severity.toUpperCase()}: ${flag.message}`).join('\n')
    : '- No safety flags recorded in this prototype review.';

  const questions = intervention.clinicianRequired
    ? [
        'What clinical interpretation should be placed on these observations?',
        'Are any further measurements, tests or treatment discussions appropriate?',
        'Are there safety concerns or contraindications the patient should know about?'
      ]
    : [
        'Are these observations useful for care planning?',
        'Is any clinical review needed before progressing the action?',
        'Are there any safety limits the patient should follow?'
      ];

  return [
    'DELTA RECORD CLINICIAN SUMMARY',
    '',
    `Patient/demo profile: ${profile.displayName}`,
    profile.description,
    '',
    'Important boundary:',
    'This summary was generated by a research prototype. It did not diagnose, treat, recommend medication, or replace clinical judgement.',
    '',
    'Intervention attempted:',
    `- ${intervention.title}`,
    `- ${intervention.patientFacingAction}`,
    '',
    'Why it was chosen:',
    ...record.rationale.map((item) => `- ${item}`),
    '',
    'Baseline signals:',
    baseline,
    '',
    'Exposure/adherence:',
    exposure,
    '',
    'Outcomes observed:',
    outcomes,
    '',
    'Attribution assessment:',
    `- ${record.attribution.confidence}: ${record.attribution.plainEnglish}`,
    ...record.attribution.reasons.map((reason) => `- ${reason}`),
    '',
    'Safety notes:',
    safety,
    '',
    'Suggested next step from prototype:',
    `- ${record.nextAction}`,
    '',
    'Questions for clinician:',
    ...questions.map((question) => `- ${question}`)
  ].join('\n');
}
